@echo	call _makereview.bat	BBX	Nokia	6101	>	BBX_Nokia_6101_Review.bat
@echo	call _makereview.bat	BBX	Nokia	6230i	>	BBX_Nokia_6230i_Review.bat
@echo	call _makereview.bat	BBX	Nokia	7260	>	BBX_Nokia_7260_Review.bat
@echo	call _makereview.bat	BBX	Nokia	7370	>	BBX_Nokia_7370_Review.bat
@echo	call _makereview.bat	BBX	Nokia	7610	>	BBX_Nokia_7610_Review.bat
@echo	call _makereview.bat	BBX	Samsung	D508	>	BBX_Samsung_D508_Review.bat
@echo	call _makereview.bat	BBX	Samsung	D608	>	BBX_Samsung_D608_Review.bat
@echo	call _makereview.bat	BBX	Motorola	E2	>	BBX_Motorola_E2_Review.bat
@echo	call _makereview.bat	BBX	Samsung	E258	>	BBX_Samsung_E258_Review.bat
@echo	call _makereview.bat	BBX	Motorola	E398	>	BBX_Motorola_E398_Review.bat
@echo	call _makereview.bat	BBX	Motorola	E6	>	BBX_Motorola_E6_Review.bat
@echo	call _makereview.bat	BBX	Nokia	E62	>	BBX_Nokia_E62_Review.bat
@echo	call _makereview.bat	BBX	Motorola	E680	>	BBX_Motorola_E680_Review.bat
@echo	call _makereview.bat	BBX	Motorola	K1	>	BBX_Motorola_K1_Review.bat
@echo	call _makereview.bat	BBX	SonyEricsson	K506	>	BBX_SonyEricsson_K506_Review.bat
@echo	call _makereview.bat	BBX	SonyEricsson	K700	>	BBX_SonyEricsson_K700_Review.bat
@echo	call _makereview.bat	BBX	SonyEricsson	K790	>	BBX_SonyEricsson_K790_Review.bat
@echo	call _makereview.bat	BBX	LG	KG90N	>	BBX_LG_KG90N_Review.bat
@echo	call _makereview.bat	BBX	Motorola	L6	>	BBX_Motorola_L6_Review.bat
@echo	call _makereview.bat	BBX	Motorola	L7	>	BBX_Motorola_L7_Review.bat
@echo	call _makereview.bat	BBX	Nokia	N73	>	BBX_Nokia_N73_Review.bat
@echo	call _makereview.bat	BBX	Nokia	N97	>	BBX_Nokia_N97_Review.bat
@echo	call _makereview.bat	BBX	SonyEricsson	S700	>	BBX_SonyEricsson_S700_Review.bat
@echo	call _makereview.bat	BBX	Motorola	V8	>	BBX_Motorola_V8_Review.bat
